// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import dotenv from "dotenv";
import dotenvExpand from "dotenv-expand";
import { defineConfig, env } from "prisma/config";

// Load and expand environment variables
const myEnv = dotenv.config();
dotenvExpand.expand(myEnv);

export default defineConfig({
  schema: "src/core/database/prisma/schema.prisma",
  migrations: {
    path: "src/core/database/prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
